version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    volumes:
      - .:/var/www/html